[package]
name = "discordshim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.11"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
prost = "0.11"
futures = "0.3"
byteorder = "1.4.3"
zip = "0.6.6"
protobuf = "3.2.0"
log = "0.4.18"
pretty_env_logger = "0.5.0"
regex = "1.9.3"

[dependencies.async-std]
version = "1.6"
features = ["attributes"]

[dependencies.uuid]
version = "1.4.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
]

[build-dependencies]
protobuf-codegen = "3.2.0"
protobuf-parse = "3.2.0"